"""laneI — génère evidence/candidates_laneI.csv (en-tête exact du brief). Scores 0-5, 5 = favorable AurumShift, '?' inconnu."""
import csv, pathlib
OUT = pathlib.Path(__file__).resolve().parents[2] / "evidence" / "candidates_laneI.csv"
H = "candidate_id,name,lane,role,gap_addressed,language,license,deployment_model,last_meaningful_release,maturity,bus_factor,price_tier,price_note,eval_level,FUNCTIONAL_FIT,SCIENTIFIC_FIT,ECONOMIC_VALUE,PIT_COMPATIBILITY,DETERMINISM,ACCURACY_OR_CALIBRATION,LATENCY,THROUGHPUT,CPU_RAM_IO,MAINTENANCE,SECURITY,API_STABILITY,INTEGRATION_COST,CUSTOM_CODE_REMOVED,SECOND_AUTHORITY_RISK,EXIT_COST,LICENSE_LEGAL_USE,TOTAL_COST,TIME_TO_OPERATIONAL_TRUTH,classification,known_failure_modes,primary_sources".split(",")
# meta: id,name,role,gap,lang,license,deploy,release,maturity,bus,tier,price_note,eval
# scores (19): FF SF EV PIT DET ACC LAT THR CPU MAINT SEC APIST INTEG CUSTOM 2ND EXIT LIC COST TTOT
R = [
 ("I01","ForexFactory export JSON/XML (nfs.faireconomy.media ff_calendar_thisweek)","ADAPTER (forward capture)","calendrier semaine : horaire + impact + forecast + previous","JSON/XML HTTP","CGU non lues (forexfactory.com 403 depuis egress) -> UNKNOWN","fichier statique Cloudflare, keyless","fichier régénéré ~horaire (Last-Modified 10:42:15Z)","mature (non documenté officiellement)","Fair Economy Inc.","TIER_A","gratuit, sans clé ; usage/redistribution UNKNOWN","L2",
  "3,2,3,2,4,2,4,1,5,3,3,2,5,2,4,5,1,5,4","SHADOW","pas d'actual (champ absent même après publication ; régénération 11:42Z sans aucun changement) ; semaine courante seulement (nextweek 404) ; 429 après ~4 req/7 min puis à nouveau 25 min plus tard (compteur partagé par l'egress) ('wait five minutes', 'updated once per hour') ; pas d'id d'occurrence (XML url = id de série) ; quasi-doublon ADP 08:15/08:16 ; JSON en ET (-04:00), XML en UTC ; CGU inconnues","https://nfs.faireconomy.media/ff_calendar_thisweek.json | https://nfs.faireconomy.media/ff_calendar_thisweek.xml"),
 ("I02","BEA release schedule ICS + release_dates.json","ORACLE (horaire officiel)","horaire prévu UTC des publications BEA (GDP, PCE, trade)","ICS/JSON","domaine public US (INFERENCE ; LAB_PRIOR 010)","fichier statique, keyless","ICS Last-Modified 2026-07-13 ; JSON file_last_updated 2026-07-13","officiel","BEA","TIER_A","gratuit","L2",
  "3,4,3,4,5,4,4,4,5,4,5,3,5,2,5,5,5,5,5","ADOPT_NOW","schedule-only (pas de valeurs) ; JSON contient 6 dates dupliquées ; fichier mis à jour rarement (juillet) -> changements de dernière minute non garantis ; DTSTAMP figé","https://www.bea.gov/news/schedule/ics/online-calendar-subscription.ics | https://apps.bea.gov/API/signup/release_dates.json"),
 ("I03","BLS release calendar ICS","ORACLE (horaire officiel)","horaire prévu ET des publications BLS (NFP, CPI, PPI, JOLTS)","ICS","domaine public, citation demandée (LAB_PRIOR 010)","fichier statique","n/a","officiel","BLS","TIER_A","gratuit","L1 (403 aujourd'hui ; L2 dans LAB_PRIOR 010)",
  "4,4,4,4,5,4,4,4,5,4,5,2,5,2,5,5,5,5,3","ADOPT_NOW","EGRESS_BLOCKED : 403 Akamai 'Access Denied' depuis cet egress le 2026-10-05 alors que LAB_PRIOR 010 l'avait lu (313 évts) -> prévoir cache + fallback FRED release dates","https://www.bls.gov/schedule/news_release/bls.ics"),
 ("I04","Fed FOMC calendar page + press RSS","ORACLE (horaire + stamp de publication forward)","dates FOMC 2026-2027, minutes, SEP ; RSS = stamp de publication réel","HTML/RSS","domaine public US (INFERENCE)","page HTML / RSS keyless","page Last-Modified 2026-09-16","officiel","Federal Reserve Board","TIER_A","gratuit","L2",
  "4,4,4,3,4,4,4,3,5,3,5,3,4,2,5,5,4,5,4","ADOPT_NOW","pas d'heure sur la page (14:00 ET = convention, INFERENCE) ; HTML change de hash sans changement de Last-Modified (contenu dynamique) -> détecter par parse, pas par hash ; dates intermeeting non planifiées","https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm | https://www.federalreserve.gov/feeds/press_all.xml"),
 ("I05","ECB Governing Council meeting calendar","ORACLE (horaire officiel)","dates réunions politique monétaire BCE","HTML","réutilisation libre avec citation (LAB_PRIOR 010)","page HTML","n/a","officiel","ECB","TIER_A","gratuit","L2",
  "3,4,3,3,4,4,4,3,5,3,5,3,4,2,5,5,5,5,4","ADOPT_NOW","pas d'heure (décision 14:15 CET = convention, INFERENCE) ; scraping HTML fragile","https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html"),
 ("I06","BoE MPC dates + BoJ MPM schedule","ORACLE (horaire officiel)","dates MPC 2026/2027 (BoE) et MPM (BoJ)","HTML","BoE : réutilisation non commerciale en général (LAB_PRIOR 010) ; BoJ UNKNOWN","pages HTML","n/a","officiel","BoE / BoJ","TIER_A","gratuit","L2",
  "3,4,3,3,4,4,4,3,5,3,5,3,4,2,5,5,3,5,4","ADOPT_NOW","BoJ : heure de décision non fixée (UNKNOWN) ; BoE 12:00 UK = convention (INFERENCE) ; parsing HTML ad hoc","https://www.bankofengland.co.uk/monetary-policy/upcoming-mpc-dates | https://www.boj.or.jp/en/mopo/mpmsche_minu/index.htm"),
 ("I07","FRED API fred/releases/dates","ORACLE (dates de release)","dates de release passées/futures, release_id stable, toutes sources US","REST JSON","FRED API ToS (clé gratuite) ; séries tierces possiblement sous copyright","REST, clé gratuite","n/a","mature","St. Louis Fed","TIER_A","gratuit avec clé","L1 (400 'api_key is not set')",
  "3,4,3,3,5,4,4,4,5,5,5,5,5,2,5,5,4,5,4","BENCH_NOW","date seulement, pas d'heure ; 'release dates ... do not necessarily represent when data will be available on FRED' ; dates futures seulement avec include_release_dates_with_no_data=true","https://fred.stlouisfed.org/docs/api/fred/releases_dates.html"),
 ("I08","Trading Economics API (calendar)","ADAPTER (fournisseur payant)","horaire + importance + consensus + TEForecast + actual + Revised + CalendarId + LastUpdate","REST","propriétaire, prix dépend de la redistribution (VENDOR_CLAIM)","SaaS","n/a","mature commercial","société","TIER_B","guest:guest supprimé (HTTP 410 MESURÉ) ; prix non lisible (JS) -> sources secondaires Standard ~149-199 USD/mois : UNVERIFIED ; essai 100 req","L1 (410)",
  "5,3,4,3,3,3,4,4,5,4,4,4,4,4,3,3,2,3,3","BENCH_NOW","LastUpdate = dernière modification (pas l'instant de publication de l'actual) ; historique = valeurs latest/révisées ? (UNKNOWN) ; tz de Date non documentée explicitement ; redistribution facturée","https://docs.tradingeconomics.com/economic_calendar/snapshot/ | https://tradingeconomics.com/api/pricing.aspx"),
 ("I09","Financial Modeling Prep /stable/economic-calendar","ADAPTER (fournisseur payant)","actual/estimate/previous/impact, historique","REST","propriétaire","SaaS","legacy v3 retiré 2025-08-31 (secondaire)","mature commercial","société","?","UNKNOWN_PRICE (pages prix/docs 403 depuis egress) ; plan gratuit 250 req/j (secondaire)","L1 (401 sans clé)",
  "4,2,3,2,3,2,4,4,5,3,4,2,4,3,3,4,2,4,3","WATCH","pas d'id d'événement ni de stamp de mise à jour connus ; tz du champ date non vérifiée ; changement d'endpoint (v3->stable) déjà subi","https://site.financialmodelingprep.com/developer/docs/economic-calendar-api"),
 ("I10","Finnhub /calendar/economic","ADAPTER","actual/estimate/prev/impact","REST","propriétaire","SaaS","n/a","mature commercial","société","?","UNKNOWN_PRICE ; 'Premium Access Required' ; 'Historical events and surprises are available for Enterprise clients' (swagger)","L1 (401)",
  "3,2,2,1,3,2,4,4,5,3,4,3,4,2,3,4,2,2,2","PARK","pas d'id, champ time sans tz, historique réservé Enterprise -> pas de backtest PIT","https://finnhub.io/static/swagger.json | https://finnhub.io/docs/api/economic-calendar"),
 ("I11","EODHD economic-events","ADAPTER","actual/previous/estimate/change depuis 2020","REST","propriétaire, plans 'Personal use'","SaaS","n/a","mature commercial","société","TIER_A","ALL-IN-ONE 99,99 USD/mois (usage personnel) ; commercial sur devis","L1 (403 avec demo)",
  "3,2,2,1,3,2,4,4,5,3,4,3,4,2,3,4,1,4,2","PARK","pas d'id ni de tz ni d'importance documentés ; usage personnel seulement","https://eodhd.com/financial-apis/economic-events-data-api | https://eodhd.com/pricing"),
 ("I12","Benzinga Calendar API (economics)","ADAPTER","id + importance 0-5 + consensus + actual + prior + updated (unix) + confirmed","REST","propriétaire","SaaS","n/a","mature commercial","société","E","UNKNOWN_PRICE (devis)","L1 (401)",
  "5,3,4,3,3,3,4,4,5,4,4,4,4,4,3,3,2,1,2","WATCH","heure en 'EST' (sans DST explicite ?) ; 'updated' = dernière modif, pas publication de l'actual ; prix sur devis","https://docs.benzinga.com/api-reference/calendar-api/get-economics.md"),
 ("I13","Polygon / Massive economic calendar","ADAPTER","calendrier éco","REST","propriétaire","SaaS","n/a","?","société","?","UNKNOWN_PRICE","L1 (404)",
  "0,?,0,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,0","REJECT","aucun endpoint calendrier éco trouvé (404 page not found)","https://api.polygon.io/v1/reference/economic-calendar"),
 ("I14","JBlanked News API (repackaging FF/MQL5)","ADAPTER","calendrier + actual + 'Outcome/Strength/Quality'","REST","UNKNOWN (chaîne de licence de la donnée FF non claire)","SaaS, clé gratuite","n/a","petit projet","1 auteur (INFERENCE)","?","free tier + payant non chiffré","L1 (401)",
  "3,1,2,1,2,1,4,3,5,2,2,1,4,2,2,4,1,4,2","REJECT","re-distribution probable de données tierces sans licence visible ; bus factor faible","https://www.jblanked.com/news/api/docs/"),
 ("I15","Investing.com economic calendar","—","calendrier + actual","HTML","CGU restrictives (pas d'API officielle)","scraping","n/a","—","—","?","pas d'API","L1 (403)",
  "2,1,1,1,1,1,?,?,?,1,1,0,1,0,2,3,0,3,1","REJECT","pas d'API officielle, 403 Cloudflare, scraping contraire aux CGU (INFERENCE)","https://www.investing.com/economic-calendar/"),
 ("I16","Econoday","ADAPTER","consensus + calendrier (fournisseur historique de consensus)","feeds","propriétaire","licence","n/a","mature","société","E","UNKNOWN_PRICE","L0 (homepage 200)",
  "4,3,3,?,?,?,?,?,?,?,?,?,2,3,3,2,?,1,1","WATCH","licence commerciale opaque ; pas d'API publique testée","https://www.econoday.com/"),
 ("I17","FXStreet calendar API","ADAPTER","calendrier + consensus","REST","propriétaire","SaaS","n/a","mature","société","?","UNKNOWN_PRICE","L1 (401 calendar-api.fxstreet.com)",
  "3,2,2,?,?,?,?,?,?,?,?,?,3,2,3,3,?,?,1","PARK","site 403, API sur clé commerciale","https://calendar-api.fxstreet.com/en/api/v1/eventDates/"),
 ("I18","Nasdaq Data Link","—","pas de calendrier éco","REST","propriétaire","SaaS","n/a","mature","société","?","—","L1 (403)",
  "0,?,0,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,0","REJECT","hors sujet calendrier","https://data.nasdaq.com/"),
 ("I19","Alpha Vantage NEWS_SENTIMENT","MODULE (score news)","news + sentiment par ticker","REST","propriétaire","SaaS","n/a","mature","société","TIER_A","free 25 req/j ; 49,99-249,99 USD/mois","L1 (clé demo refusée)",
  "2,1,2,1,2,1,4,2,5,3,4,3,4,1,3,4,3,4,2","PARK","sentiment boîte noire, pas de stamp de publication garanti","https://www.alphavantage.co/premium/"),
 ("I20","GDELT 2.0 bulk (Events/Mentions/GKG 15 min)","ADAPTER (forward capture news)","flux news mondial structuré, PIT par fichier","CSV zip","ouvert, attribution","fichiers keyless","fichier 20261005111500 publié 11:05:56Z","mature","GDELT Project","TIER_A","gratuit","L2",
  "2,2,2,4,4,2,4,4,4,4,4,4,3,1,5,5,4,5,2","SHADOW","DATEADDED (11:15:00) postérieur de ~9 min au Last-Modified réel (11:05:56) -> stamp nominal, conservateur ; bruit élevé ; DOC API : 429 puis réponse vide {} en 24 s (PARK)","https://data.gdeltproject.org/gdeltv2/lastupdate.txt | https://api.gdeltproject.org/api/v2/doc/doc"),
 ("I21","NewsAPI.org","ADAPTER","news généralistes","REST","Developer : interdit prod/commercial","SaaS","n/a","mature","société","C","Business 449 USD/mois ; Advanced 1 749 ; free = 24 h de retard, dev only","L1 (401)",
  "2,1,1,2,3,1,3,3,5,3,4,3,4,1,4,4,2,1,2","REJECT","free inutilisable (retard 24 h, non-prod) ; prix élevé pour valeur non démontrée","https://newsapi.org/pricing"),
 ("I22","CryptoPanic API","ADAPTER","news crypto agrégées + votes","REST","propriétaire","SaaS","n/a","mature","petite société","?","UNKNOWN_PRICE ; endpoint 'developer' rejeté : 'Valid paths are /api/{growth|growth_weekly|enterprise}/v2' (MESURÉ)","L1 (404)",
  "2,1,2,2,3,1,4,3,5,2,3,2,4,1,4,4,2,3,2","PARK","palier gratuit apparemment supprimé ; votes mutables (lookahead)","https://cryptopanic.com/developers/api/"),
 ("I23","CCData / CoinDesk Data news API","ADAPTER","news crypto horodatées","REST","propriétaire","SaaS","n/a","mature","société","?","UNKNOWN_PRICE (401 sans clé)","L1 (401)",
  "2,1,2,2,3,1,4,3,5,3,4,3,4,1,4,4,2,3,2","PARK","clé requise ; valeur incrémentale non démontrée (LAB_PRIOR 016 : news non testées)","https://data-api.coindesk.com/news/v1/article/list"),
 ("I24","RavenPack / Bigdata.com","ADAPTER","news analytics entités/événements PIT","REST","propriétaire","SaaS","n/a","mature","société","E","UNKNOWN_PRICE (devis)","L0",
  "3,3,2,4,3,3,4,4,4,4,4,4,3,2,3,2,2,0,1","WATCH","coût E ; preuve d'apport sur crypto intraday absente","https://www.bigdata.com/"),
 ("I25","Dow Jones Factiva / DJ Newswires","ADAPTER","news institutionnelles horodatées","feeds","propriétaire","licence","n/a","mature","société","E","UNKNOWN_PRICE (devis)","L0",
  "2,2,1,4,3,2,4,4,4,4,4,4,2,1,3,2,2,0,1","PARK","coût E disproportionné pour PAPER BTC/DOGE","https://www.dowjones.com/professional/factiva/"),
 ("I26","Event Registry (newsapi.ai)","ADAPTER","news + événements clusterisés","REST","propriétaire","SaaS","n/a","mature","société","?","UNKNOWN_PRICE (401)","L1 (401)",
  "2,1,1,2,3,1,4,3,5,3,4,3,4,1,4,4,2,3,2","PARK","clé requise, valeur non démontrée","https://eventregistry.org/"),
 ("I27","Polymarket Gamma + CLOB prices-history + data-api trades","ORACLE / SHADOW (probabilités d'événement)","proba marché décision Fed / macro, PIT natif (timestamps)","REST","CGU non lues ; trading géobloqué FR/US/UK/DE (doc) ; lecture publique","REST keyless","marché Oct-2026 créé 2026-06-17","mature","société","TIER_A","gratuit (lecture)","L2",
  "4,3,3,4,4,4,4,4,5,3,4,3,4,2,4,5,2,5,4","SHADOW","prices-history : fenêtre startTs/endTs <=15 j (18 j -> 400) ; interval=max ne rend que ~30 j ; interval=all fidelity=1440 = journalier depuis création ; pas d'historique carnet ; résolution mutable (UMA) ; CGU redistribution UNKNOWN","https://docs.polymarket.com/api-reference/rate-limits.md | https://docs.polymarket.com/api-reference/geoblock.md | https://clob.polymarket.com/prices-history"),
 ("I28","Kalshi Trade API v2 (KXFED/KXCPI/KXPAYROLLS : markets, candlesticks, trades, historical/*)","ORACLE / SHADOW (probabilités d'événement)","distribution implicite taux Fed / CPI / NFP, candles 1m/1h/1j, trades horodatés µs","REST","CGU/Developer Agreement non lus (429) -> UNKNOWN ; marché régulé CFTC","REST keyless (lecture)","API v3.32.0 (openapi)","mature","société régulée","TIER_A","gratuit (lecture)","L2",
  "4,4,3,5,4,4,4,4,5,3,4,3,4,2,4,5,2,5,4","SHADOW","schéma migré vers *_fp/*_dollars (champs legacy null) ; updated_time = métadonnée, pas l'heure de cote ; données > cutoff (2026-08-06) sur /historical/* ; 1m limité à 5000 bougies/req ; forecast_percentile_history -> 400 (FAILED L1)","https://docs.kalshi.com/llms.txt | https://docs.kalshi.com/getting_started/historical_data.md | https://api.elections.kalshi.com/trade-api/v2/series/KXFED"),
 ("I29","Manifold Markets API","—","marchés de prédiction play-money","REST","CGU Manifold","REST keyless","n/a","actif","société","TIER_A","gratuit","L1 (200)",
  "1,1,1,4,4,1,4,4,5,3,4,3,4,0,4,5,3,5,2","PARK","monnaie fictive, peu de liquidité macro -> faible signal","https://api.manifold.markets/v0/markets"),
 ("I30","FinBERT (ProsusAI/finbert)","MODULE (classif. sentiment)","sentiment titres financiers","Python/PyTorch","licence HF repo (non vérifiée ici) ","local CPU","modèle 2020","figé","ProsusAI","TIER_A","gratuit","L1 (smoke 8 titres x4)",
  "1,1,1,4,5,1,2,2,3,2,5,4,4,0,5,5,3,5,3","REJECT","3 erreurs flagrantes sur 8 titres (payrolls beat -> negative 0,956 ; hack 200 M$ -> neutral 0,94 ; ECB cut -> negative) ; 1,1-1,45 s/titre CPU ; hub HF client bloqué (xet) via proxy, fichiers via curl OK","https://huggingface.co/ProsusAI/finbert"),
 ("I31","FinGPT","MODULE","LLM financier fine-tuné","Python","MIT (repo) + licences des modèles de base","local GPU","n/a","recherche","AI4Finance","TIER_A","gratuit + GPU","L0",
  "1,2,1,1,2,?,1,1,1,2,4,2,2,0,4,4,3,3,1","PARK","fuite de knowledge cutoff en backtest ; GPU ; pas de gain démontré","https://github.com/AI4Finance-Foundation/FinGPT"),
 ("I32","transformers zero-shot (NLI) classif. d'événements","MODULE","catégoriser titres -> types d'événements","Python","Apache-2.0","local","n/a","mature","HF","TIER_A","gratuit","L0",
  "2,1,1,3,4,?,2,2,3,4,5,4,4,1,5,5,5,5,3","PARK","précision non mesurée ; latence CPU comparable à FinBERT","https://github.com/huggingface/transformers"),
 ("I33","LLM structuré (classification d'événements via API)","MODULE (offline/shadow)","extraction structurée type/entité/sens d'un titre","API","propriétaire","SaaS","n/a","mature","fournisseurs","?","coût au token (non chiffré ici)","L0",
  "3,2,2,1,1,?,2,3,5,3,3,2,4,1,3,4,3,3,2","PARK","knowledge cutoff -> fuite en backtest historique (le modèle 'connaît' l'issue) ; non-déterminisme ; à n'utiliser qu'en forward/shadow avec version figée","—"),
 ("I34","OKX /api/v5/support/announcements (listings/delistings)","ADAPTER (événements crypto)","listings/delistings/trading updates avec pTime (ms) et businessPTime","REST","CGU OKX API (non relues ici)","REST keyless","n/a","mature","OKX","TIER_A","gratuit","L2",
  "3,3,3,4,4,3,4,3,5,3,4,3,5,2,5,5,3,5,4","BENCH_NOW","~7 pages x 20 annonces -> profondeur ~11 mois ; contenu dépendant de la région de l'IP (types 'trading-updates-us-aus' vus) ; annonces-types endpoint exige auth (7002)","https://www.okx.com/api/v5/support/announcements?annType=announcements-new-listings"),
 ("I35","Tokenomist (token unlocks)","ADAPTER (événements crypto)","calendrier d'unlocks/émissions","REST","propriétaire","SaaS","n/a","mature","société","?","UNKNOWN_PRICE (plans Standard/Elite/Enterprise, essai gratuit)","L0",
  "2,2,2,2,3,2,4,3,5,3,4,3,4,1,4,4,2,3,2","WATCH","peu pertinent pour BTC/DOGE (pas de vesting) ; utile si univers C0 s'étend","https://docs.tokenomist.ai/api-documents"),
]
with open(OUT, "w", newline="", encoding="utf8") as f:
    w = csv.writer(f, quoting=csv.QUOTE_NONNUMERIC)
    f.write(",".join(H) + "\n")
    for r in R:
        cid, name, role, gap, lang, lic, dep, rel, mat, bus, tier, pnote, ev, scores, cls, fail, src = r
        sc = scores.split(",")
        assert len(sc) == 19, (cid, len(sc))
        sc = [int(s) if s.isdigit() else "?" for s in sc]
        w.writerow([f"laneI-{cid}", name, "laneI", role, gap, lang, lic, dep, rel, mat, bus, tier, pnote, ev] + sc + [cls, fail, src])
print(OUT, len(R))
