import json
from probe_lib import call
T=[
("hyperliquid_info","https://api.hyperliquid.xyz/info","POST",{"type":"metaAndAssetCtxs"}),
("hyperliquid_candle","https://api.hyperliquid.xyz/info","POST",{"type":"candleSnapshot","req":{"coin":"BTC","interval":"1m","startTime":1790680000000,"endTime":1790686000000}}),
("hyperliquid_funding","https://api.hyperliquid.xyz/info","POST",{"type":"fundingHistory","coin":"BTC","startTime":1790000000000}),
# FX
("frankfurter_latest","https://api.frankfurter.dev/v1/latest?base=EUR&symbols=USD,JPY,GBP,CHF",None,None),
("frankfurter_hist","https://api.frankfurter.dev/v1/2020-01-01..2020-03-01?base=EUR&symbols=USD",None,None),
("open_er_api","https://open.er-api.com/v6/latest/USD",None,None),
("fawaz_currency","https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies/usd.json",None,None),
("ecb_eurofxref","https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml",None,None),
("ecb_sdmx_fx","https://data-api.ecb.europa.eu/service/data/EXR/D.USD.EUR.SP00.A?lastNObservations=5&format=jsondata",None,None),
("ecb_sdmx_fx_hist","https://data-api.ecb.europa.eu/service/data/EXR/D.USD.EUR.SP00.A?startPeriod=1999-01-04&endPeriod=1999-01-10&format=jsondata",None,None),
("exchangerate_host","https://api.exchangerate.host/latest?base=USD",None,None),
("yahoo_chart_xau","https://query1.finance.yahoo.com/v8/finance/chart/GC=F?interval=1h&range=5d",None,None),
("yahoo_chart_eurusd","https://query2.finance.yahoo.com/v8/finance/chart/EURUSD=X?interval=1h&range=5d",None,None),
("stooq_xau","https://stooq.com/q/d/l/?s=xauusd&i=d",None,None),
("stooq_pl","https://stooq.pl/q/d/l/?s=xauusd&i=d",None,None),
("dukascopy_bi5","https://datafeed.dukascopy.com/datafeed/XAUUSD/2024/00/02/10h_ticks.bi5",None,None),
("gold_api_xau","https://api.gold-api.com/price/XAU",None,None),
("gold_api_xag","https://api.gold-api.com/price/XAG",None,None),
("goldprice_org","https://data-asg.goldprice.org/dbXRates/USD",None,None),
("metals_live","https://api.metals.live/v1/spot",None,None),
("swissquote_xau","https://forex-data-feed.swissquote.com/public-quotes/bboquotes/instrument/XAU/USD",None,None),
("lbma_gold_am","https://prices.lbma.org.uk/json/gold_am.json",None,None),
("kraken_paxg","https://api.kraken.com/0/public/OHLC?pair=PAXGUSD&interval=60",None,None),
("kraken_xauusd_fx","https://api.kraken.com/0/public/OHLC?pair=XAUTUSD&interval=60",None,None),
("okx_xaut","https://www.okx.com/api/v5/market/candles?instId=XAUT-USDT&bar=1H",None,None),
("coinbase_paxg","https://api.exchange.coinbase.com/products/PAXG-USD/candles?granularity=3600",None,None),
("deribit_paxg_perp","https://www.deribit.com/api/v2/public/get_tradingview_chart_data?instrument_name=PAXG_USDC-PERPETUAL&resolution=60&start_timestamp=1790000000000&end_timestamp=1790680000000",None,None),
("okx_swap_xaut","https://www.okx.com/api/v5/market/candles?instId=XAUT-USDT-SWAP&bar=1H",None,None),
("hl_xyz_gold","https://api.hyperliquid.xyz/info","POST",{"type":"allMids","dex":"xyz"}),
# commodities / macro
("fred_csv_dgs10","https://fred.stlouisfed.org/graph/fredgraph.csv?id=DGS10",None,None),
("fred_csv_wti","https://fred.stlouisfed.org/graph/fredgraph.csv?id=DCOILWTICO",None,None),
("fred_csv_gold","https://fred.stlouisfed.org/graph/fredgraph.csv?id=GOLDAMGBD228NLBM",None,None),
("fred_api_nokey","https://api.stlouisfed.org/fred/series/observations?series_id=DGS10&file_type=json",None,None),
("alfred_csv_vintage","https://alfred.stlouisfed.org/graph/fredgraph.csv?id=GDPC1&vintage_date=2020-01-30",None,None),
("eia_nokey","https://api.eia.gov/v2/petroleum/pri/spt/data/?frequency=daily&data[0]=value",None,None),
("bls_api_v1","https://api.bls.gov/publicAPI/v1/timeseries/data/CUUR0000SA0",None,None),
("treasury_fiscal","https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/avg_interest_rates?page[size]=3",None,None),
("treasury_yield_csv","https://home.treasury.gov/resource-center/data-chart-center/interest-rates/daily-treasury-rates.csv/2026/all?type=daily_treasury_yield_curve&field_tdr_date_value=2026&page&_format=csv",None,None),
("nyfed_sofr","https://markets.newyorkfed.org/api/rates/secured/sofr/last/5.json",None,None),
("worldbank","https://api.worldbank.org/v2/country/US/indicator/NY.GDP.MKTP.CD?format=json&per_page=5",None,None),
("worldbank_pink","https://thedocs.worldbank.org/en/doc/5d903e848db1d1b83e0ec8f744e55570-0350012021/related/CMO-Historical-Data-Monthly.xlsx",None,None),
("imf_datamapper","https://www.imf.org/external/datamapper/api/v1/NGDP_RPCH/USA",None,None),
("eurostat","https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/prc_hicp_manr?geo=EA&coicop=CP00&lastTimePeriod=3",None,None),
("oecd_sdmx","https://sdmx.oecd.org/public/rest/data/OECD.SDD.STES,DSD_KEI@DF_KEI,4.0/USA.M.CPI.PA._Z.?lastNObservations=3&format=jsondata",None,None),
("cftc_cot","https://publicreporting.cftc.gov/resource/6dca-aqww.json?$limit=3&$order=report_date_as_yyyy_mm_dd DESC",None,None),
("bea_nokey","https://apps.bea.gov/api/data?method=GETDATASETLIST&ResultFormat=JSON",None,None),
("bankofcanada","https://www.bankofcanada.ca/valet/observations/FXUSDCAD/json?recent=5",None,None),
("boe_iadb","https://www.bankofengland.co.uk/boeapps/database/_iadb-fromshowcolumns.asp?csv.x=yes&Datefrom=01/Sep/2026&Dateto=now&SeriesCodes=XUDLUSS&CSVF=TN&UsingCodes=Y&VPD=Y&VFD=N",None,None),
("snb","https://data.snb.ch/api/cube/devkum/data/json/en",None,None),
# calendar/news
("ff_calendar","https://nfs.faireconomy.media/ff_calendar_thisweek.json",None,None),
("ff_calendar_xml","https://nfs.faireconomy.media/ff_calendar_thisweek.xml",None,None),
("fed_fomc_cal","https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",None,None),
("bls_schedule_ics","https://www.bls.gov/schedule/news_release/bls.ics",None,None),
("gdelt_doc","https://api.gdeltproject.org/api/v2/doc/doc?query=bitcoin&mode=artlist&maxrecords=5&format=json",None,None),
("cryptopanic_nokey","https://cryptopanic.com/api/v1/posts/?public=true",None,None),
("fear_greed","https://api.alternative.me/fng/?limit=3",None,None),
("blockchain_info","https://api.blockchain.info/charts/hash-rate?timespan=5days&format=json",None,None),
("mempool_space","https://mempool.space/api/v1/prices",None,None),
("tradingeconomics_guest","https://api.tradingeconomics.com/calendar?c=guest:guest&f=json",None,None),
("fmp_nokey","https://financialmodelingprep.com/api/v3/economic_calendar",None,None),
("finnhub_nokey","https://finnhub.io/api/v1/calendar/economic",None,None),
("alphavantage_demo","https://www.alphavantage.co/query?function=FX_DAILY&from_symbol=EUR&to_symbol=USD&apikey=demo",None,None),
("twelvedata_demo","https://api.twelvedata.com/time_series?symbol=EUR/USD&interval=1h&apikey=demo",None,None),
("polygon_nokey","https://api.polygon.io/v2/aggs/ticker/C:EURUSD/range/1/hour/2026-09-01/2026-09-05",None,None),
("oanda_nokey","https://api-fxpractice.oanda.com/v3/instruments/EUR_USD/candles",None,None),
]
res=[]
for n,u,m,b in T:
    o=call(n,u,method=m or "GET",body=b)
    j=o.get("json"); s=(json.dumps(j)[:130] if j is not None else (o.get("text") or o.get("err") or "")[:130].replace("\n"," "))
    print(f"{n:24s} {o.get('status')} {o.get('ms')}ms {o.get('bytes')}B | {s}")
    res.append({k:v for k,v in o.items() if k not in("json","text")})
json.dump(res,open("../results/sweep2.json","w"),indent=1)
