"""Primitive catalog: 15 executed contracts (pre-declared) + discovered-not-executed. Generates report tables (02, 03) and the discovery counts."""
FS, FSR, OFF, LA = "FORWARD_SAFE", "FORWARD_SAFE_WITH_RECEIPT_STAMP", "OFFLINE_ONLY", "LOOKAHEAD_RISK"
# id: mechanism, formula, inputs, sampling, horizon, failure modes, lookahead risk (specific), class, sources
X = {
"P01_TSMOM": ("Under-reaction / herding: past vol-scaled return persists (time-series momentum).", "s = ½·[r24/(σ·√24) + r72/(σ·√72)], r_n = ln(C_t/C_{t-n}), σ = 720h rolling std of 1h log returns. w = clip(s/std_720(s),±1)/N.", "Perp 1h close", "1h bars; decision at bar close", "24h primary, 4h secondary", "Trend reversals (V-shapes), chop regimes, momentum crashes after sharp drawdowns.", "Only closed-bar closes ≤ t; σ trailing. No centered filter.", FS, "S1,S2c (landscape B); DOCUMENTED_CLAIM only"),
"P02_XS_RS7D": ("Cross-sectional relative strength: winners over 7d keep outperforming within a liquid basket.", "s = ln(C_t/C_{t-168})/(σ√168); dollar-neutral: CS-demeaned clipped z, gross 1.", "Perp 1h close, 10 assets", "1h, 24h hold", "24h primary, 4h secondary", "Basket dominated by one factor (BTC beta); sector rotations; only 10 assets (thin cross-section).", "Universe fixed ex ante (no survivorship filter by future liquidity) — 10 majors alive throughout, so survivorship bias exists (assets chosen with hindsight of being liquid in 2026).", FS, "S1,S3 (landscape B)"),
"P03_REV4H": ("Liquidity-provision / overreaction: 1–4h moves partly reverse.", "s = −ln(C_t/C_{t-4})/(σ√4). TS mode.", "Perp 1h close", "1h, 4h hold", "4h primary, 24h secondary", "Trending regimes; turnover ≫ edge (cost-dominated); larger coins show momentum not reversal.", "Bar t closed before decision; no partial bar.", FS, "S3,S4 (landscape B)"),
"P04_VOLCOMP_BRK": ("Vol compression → expansion: breakout after low realised range resolves directionally.", "comp_t = [mean_24(PK)/mean_720(PK)]_{t-1} < 0.7 (Parkinson variance); s = 1[C_t>max H_{t-48..t-1}] − 1[C_t<min L_{t-48..t-1}] if comp else 0.", "Perp 1h OHLC", "1h", "24h primary, 4h secondary", "False breakouts, sparse signal (few trades → low power), gap-like moves.", "Donchian and compression windows shifted by one bar (exclude current bar); no in-progress-bar squeeze.", FS, "generic (no verified academic source; landscape A gap)"),
"P05_BRK_PERSIST": ("Breakout persistence baseline: position within 48h Donchian range, continuous.", "s = (C_t − minL_48)/(maxH_48 − minL_48) − ½.", "Perp 1h OHLC", "1h", "24h primary, 4h secondary", "Range-bound markets; overlaps P01 by construction (baseline for redundancy).", "Window includes bar t (closed) only.", FS, "generic"),
"P06_FUND_CARRY": ("Carry: perp longs pay funding when leverage demand is high; short crowded / long uncrowded earns carry and fades crowding.", "s = −mean_72h(f_ph), f_ph = last settled funding / interval_h (per-hour), ffilled from settlement stamp. CS mode, dollar-neutral.", "Binance USD-M funding history", "8h (some assets 4h) settlement, ffilled hourly", "24h primary, 4h secondary", "Funding regime shifts; funding can stay extreme; delta-one carry needs spot leg (not modelled — this is a directional CS perp book).", "Uses settled funding only (never predicted); stamp = calc time floored to hour → visible next decision. Real-time receipt latency not in archive.", FSR, "S1,S5 (landscape A/B)"),
"P07_PREMIUM": ("Basis: perp premium over index reflects leveraged demand; large positive deviations mean-revert.", "s = −(mean_4(prem) − mean_720(prem)), prem = Binance premium-index kline close.", "Binance premium index klines", "1h", "4h primary, 24h secondary", "Premium is small vs. costs; structural drift; correlated with P03.", "Exchange-derived index; archive gives no receipt time; bar closed.", FSR, "S5 (landscape A)"),
"P08_OI_PRICE": ("OI–price divergence: OI rising with the move = new leveraged positions confirm trend; OI falling = short-covering.", "s = sign(r24)·ΔlnOI_24/(σ_OI·√24) with OI = coin-denominated open interest, lagged +1h.", "Binance metrics (5-min OI snapshots) → hourly last, lagged 1 bar", "5-min → 1h", "24h primary, 4h secondary", "OI notional vs contracts confusion; venue OI is one venue only; snapshot stamp semantics unverified.", "Extra 1-bar receipt lag applied to compensate unknown publication delay of bulk metrics.", FSR, "S4,S7,S9 (landscape A); no verified predictive source (gap)"),
"P09_OI_FLUSH": ("Liquidation-pressure proxy: sharp OI collapse alongside a large move indicates forced closing that overshoots; fade it.", "big_t = |r6|/(σ√6)>1.5; s = −sign(r6)·max(0, −z_ΔOI6 − 1) if big else 0.", "Binance OI metrics + closes", "1h", "4h primary, 24h secondary", "Proxy only (true liquidation tape not available historically); rare events → low power; cascades can continue.", "OI lagged 1 bar; thresholds fixed ex ante.", FSR, "S9,S10 (landscape A)"),
"P10_TAKER_IMB": ("Order-flow persistence: net aggressive buying predicts near-term continuation (price impact of signed flow).", "s = Σ_4h(2·TBQ − QV)/Σ_4h QV (taker-buy quote volume from kline).", "Perp 1h kline taker-buy volume", "1h", "4h primary, 24h secondary", "Flow already in price by bar close; high turnover.", "Kline volumes are final at close.", FS, "S12,S13,S14 (landscape A)"),
"P11_LIQ_SHOCK": ("Liquidity shock: on abnormal volume (z>1.5) the concurrent 1h move contains liquidity-driven overshoot.", "s = −r1/σ if z(ln QV; 168h) > 1.5 else 0.", "Perp 1h close, quote volume", "1h", "4h primary, 24h secondary", "Volume shocks are often informed (news) → continuation, not reversal; sparse.", "z uses trailing window incl. current closed bar.", FS, "S16,S17 (landscape A)"),
"P12_LEADLAG_BTC": ("Cross-asset lead/lag: alts under-react to BTC moves over 1–4h.", "s_a = (β_a·r^{BTC}_2h − r^a_2h)/(σ√2), β = 720h rolling OLS beta; BTC excluded from the book. CS mode on 9 alts.", "Perp 1h closes", "1h", "4h primary, 24h secondary", "Alt beta instability, execution latency ≥ effect duration (often minutes), cost-dominated at 1h.", "β uses returns ≤ t only.", FS, "S10,S11 (landscape B)"),
"P13_SEASON_HOD": ("Intraday seasonality (hour-of-day): trailing same-hour mean returns.", "s = Σ_{j=1..H} (1/60)Σ_{i=1..60} r_{t+j−24i}, all indices ≤ t.", "Perp 1h close", "1h, UTC hours", "4h primary, 24h secondary", "Effect instability (documented contradiction S14 vs S16); data-snooping if hour chosen ex post (not done here).", "Trailing 60-day same-hour means only; verified by truncation test.", FS, "S14,S15,S16 (landscape B)"),
"P14_VRP_DVOL": ("Realized vs implied vol: implied above realised (vs own trailing mean) = compensated risk-bearing.", "s = [DVOL_{t-1} − RV_168h(t)] − mean_2160(same); RV=std of 1h log returns·√8760·100. BTC & ETH only.", "Deribit DVOL hourly + closes", "1h", "24h primary, 4h secondary", "Only 2 assets → low power; DVOL is 30d-forward implied while horizon is 24h.", "DVOL lagged one bar (candle stamping convention unverified); trailing RV only — forward RV variant excluded (LOOKAHEAD_RISK).", FSR, "S19,S20 (landscape A/B)"),
"P15_FUND_DIV": ("Funding divergence: Binance funding above Hyperliquid funding signals venue-specific crowding.", "s = −[mean_24(f^{BN}_ph) − mean_24(f^{HL}_ph)]. CS mode.", "Binance + Hyperliquid funding histories", "1h (HL) / 8h (BN) → 1h", "24h primary, 4h secondary", "HL funding has different clamps/definitions; 2023-06+ only; venue-specific.", "Both stamps floored to the hour and visible at the next decision; HL time jitter (ms) handled by flooring.", FSR, "S1,S5; cross-venue funding comparison in report 005"),
}
# discovered, not executed: id, name, family, class, reason
D = [
("D16","Dated-futures term-structure slope (Deribit)","term structure",FSR,"no public point-in-time curve history for expired instruments in bulk"),
("D17","Perp vs dated-future basis","basis",FSR,"same PIT-curve gap as D16"),
("D18","Macro event reaction (FOMC/CPI first-print surprise)","event-driven macro",FSR,"needs first-release stamps + ex-ante consensus vintages; using revised prints would be LOOKAHEAD_RISK; 3.7y sample has ~40 FOMC/CPI events (power)"),
("D19","Realized Amihud illiquidity","liquidity shocks",FS,"overlaps P11; source S18 not verifiable"),
("D20","Top-trader long/short ratio contrarian","positioning",FSR,"metrics available; deprioritised as redundant with funding/OI family"),
("D21","True liquidation-stream intensity (forceOrder/HL/OKX)","liquidation pressure",FSR,"public streams are sampled/partial; no complete history (report 005)"),
("D22","HMM regime gating with smoothed states","regime-conditioned",LA,"smoothed/full-sample fit uses the future; filtered-probability variant is FSR"),
("D23","Offline change-point segmentation (ruptures-style)","regime-conditioned",OFF,"offline by construction"),
("D24","Centered MA / HP / smoothed Kalman trend","momentum/trend",LA,"centered filter uses future bars"),
("D25","Full-sample z-normalised features","generic",LA,"future-normalised scale"),
("D26","Quarter-hour order-imbalance effect (Kim & Hansen 2026)","volume imbalance",FS,"needs trade-level tape; too heavy for this pass"),
("D27","CTREND ML trend factor (Fieberg et al. JFQA 2025)","momentum/trend",FSR,"ML, needs walk-forward and >3000-coin universe"),
("D28","First-half-hour → last-half-hour intraday momentum (Shen et al.)","intraday seasonality",FS,"session definition ex ante; overlaps P01/P13 at 1h resolution"),
("D29","FX fixing seasonality (Krohn-Mueller-Whelan)","intraday seasonality",FSR,"needs FX/gold intraday history and DST-exact stamps"),
("D30","FX/crypto carry (rate differential)","carry",FSR,"needs point-in-time rates"),
("D31","BTC vs equity/macro lead-lag","cross-asset lead/lag",FSR,"needs synchronised equity ticks"),
("D32","VRP with realised forward variance (DVOL − RV_fwd)","realized vs implied vol",LA,"uses future RV; ex-post analysis only"),
("D33","Predicted (next-period) funding from premium index","carry",FSR,"predicted-vs-settled definitions differ by venue"),
("D34","Bollinger/Keltner squeeze evaluated on the in-progress bar","vol compression",LA,"intrabar lookahead (repainting)"),
]
def counts():
    ex = list(X.values()); cl = [v[7] for v in ex] + [d[3] for d in D]
    return dict(discovered=len(X) + len(D), executed=len(X), fs=cl.count(FS), fsr=cl.count(FSR), off=cl.count(OFF), la=cl.count(LA))
