"""Per-candidate adjudication. Fields: name -> (class, executed, svc, ds, license_flag, evidence)
class: ADOPT_REFERENCE | ADAPT_CANDIDATE | PARK | REJECT
executed: EXEC (behavioural microtest run) | INSTALL (installed/imported only) | NO
svc: needs a separately operated network service beyond host process + existing PostgreSQL (Y/N)
ds : needs its own persistent datastore to be useful (Y/N)
Evidence labels: PROVEN (test with independent ground truth), OBSERVED (ran/inspected), DOCUMENTED_CLAIM, INFERENCE, UNKNOWN."""
A = {
"ccxt": ("ADAPT_CANDIDATE","EXEC","N","N","MIT","OBSERVED: fetch_ohlcv 100x1m OK on kraken/coinbase/okx/bitstamp (60 s step); binance 451 & bybit 403 = egress. All returned the forming bar; trades carry no receipt stamp. Needs wrapper for receipt time, forming-bar drop, unit normalisation."),
"cryptofeed": ("ADAPT_CANDIDATE","EXEC","N","N","AGPL-3.0-or-later (flag)","OBSERVED: 20 s live WS: Kraken 38 trades, Bitstamp 24, each callback gets a local `receipt` stamp next to exchange ts. Coinbase symbol discovery 401 (auth now required). Needs event-loop workaround on py3.11+uvloop. 39 commits/12 m, top author 74 %."),
"binance-public-data": ("ADOPT_REFERENCE","EXEC","N","N","no LICENSE file at HEAD (UNKNOWN)","OBSERVED: downloaded BTCUSDT-1m-2025-03 + .CHECKSUM (sha256 matches, verified by us; script only downloads it, never verifies), 44 640 rows, 16-digit (µs) open_time. Use as layout/reference; code reuse blocked by missing licence."),
"freqtrade": ("PARK","NO","N","N","GPL-3.0 (flag)","DOCUMENTED_CLAIM/INFERENCE: a live-capable bot application with its own sqlite; extracting the data downloader means adopting a runtime with order authority. Not executed."),
"hummingbot": ("PARK","NO","N","N","Apache-2.0","INFERENCE: live market-making bot + Docker/Gateway runtime (README); order authority is the product. Not executed."),
"yfinance": ("PARK","EXEC","N","N","Apache-2.0","OBSERVED: 5 daily AAPL rows in 0.7 s; direct curl to the Yahoo chart endpoint returned 429. Unofficial scraper of a consumer site (ToS/stability risk, INFERENCE)."),
"openbb": ("PARK","NO","N","N","Apache-2.0","Aggregator platform (135 commits/12 m, 73 % one author). Not executed; overlaps with source-level clients."),
"databento-python": ("PARK","NO","N","N","Apache-2.0","Client is OSS, data is paid + key required; not executed (no key)."),
"tardis-python": ("ADAPT_CANDIDATE","EXEC","N","N","MPL-2.0","OBSERVED: keyless first-day-of-month sample works: Deribit BTC-PERPETUAL trades 2025-03-01 = 131 910 rows, columns include `timestamp` AND `local_timestamp` (receipt side). Anything beyond free sample is commercial data (DOCUMENTED_CLAIM). Composes with hftbacktest converter scripts (present in repo tree)."),
"pandas-datareader": ("PARK","NO","N","N","BSD-3-Clause","Thin per-source wrappers, 2 releases/12 m, 86 % one author. Not executed."),
"findatapy": ("PARK","NO","N","N","Apache-2.0","11 commits/12 m, one author. Not executed."),
"hftbacktest": ("ADAPT_CANDIDATE","EXEC","N","N","MIT","PROVEN vs hand derivation (risk-adverse queue: fill at 8.0 s); the three probabilistic queue models gave the same 8.0 s in this single scenario (not discriminating); order latency: 4 s latency -> no fill (position 0), 1.5 s latency -> filled position but not visible to the strategy inside the feed window (INFERENCE: response latency); maker-fee model booked -0.01 on a 100.0 fill; 3 runs bit-identical; 10.9-11.8 M events/s warm. Slowed upstream: last commit 2025-12-23, 24 commits/12 m, top author 62 %; only 1 test file visible by path (Rust inline tests not counted)."),
"nautilus_trader": ("ADAPT_CANDIDATE","EXEC","N","N","LGPL-3.0-or-later (flag)","OBSERVED: L2 delta replay OK, deterministic (identical event hash x2), 349-360 k quotes/s, fills when simulated book crosses. A print-driven passive fill with queue position was NOT reproduced in 9 configs (UNKNOWN whether supported). 574 MB env, full live-trading framework (runtime authority to be kept disabled), 127 authors but top 85 %."),
"abides-jpmc-public": ("PARK","EXEC","N","N","BSD-3-Clause","OBSERVED: runs only on py3.9 with 2020-era pins (numpy 1.22, pandas 1.2.4, pomegranate 0.14.5 has no cp311 wheel); rmsc04 1117 agents, seed-deterministic, seed-sensitive. No commits since 2023-12."),
"abides-gym-markets": ("REJECT","NO","N","N","BSD-3-Clause (GT)","Last commit 2020-11; superseded by jpmc fork. Not executed."),
"orderbook (dyn4mik3)": ("REJECT","EXEC","N","N","MIT","OBSERVED: PyPI 0.1.2 (2013) fails at import (circular import); GitHub HEAD matches FIFO ground truth but get_volume_at_price raises AttributeError; ~121-150 k orders/s; matching engine only (no feed ingestion/queue tracking/latency/clock)."),
"vectorbt": ("PARK","EXEC","N","N","Apache-2.0 + Commons Clause (not OSI)","OBSERVED: SMA20/50 = 57 trades, final value equal to backtrader to 1e-8; 22 s first call (numba JIT), 8 s import; whole-array API exposes future by construction (foresight signal earns +7.5 % at zero fees when handed in as an array)."),
"backtrader": ("PARK","EXEC","N","N","GPL-3.0+ (flag)","OBSERVED: 57 trades, equal to vectorbt/oracle; direct data.close[+1] returns a future bar on preloaded data (leak) except on last bar; last release 2023-04, 0 commits/12 m."),
"backtesting.py": ("ADOPT_REFERENCE","EXEC","N","N","AGPL-3.0 (flag)","PROVEN vs 20-line numpy oracle: same 57 trades, equity 0.977346 vs 0.97741; deterministic; 0.65 s; per-bar API raises IndexError on future index. Use as cross-check oracle only (AGPL, 6 test files)."),
"zipline-reloaded": ("PARK","EXEC","N","Y","Apache-2.0","OBSERVED: csvdir ingest + daily algo runs, deterministic; ingest strictly rejects non-session (weekend) bars (calendar gate). Own bundle store, equity/daily orientation; 4 commits/12 m by one author."),
"bt": ("PARK","EXEC","N","N","MIT","OBSERVED: runs deterministically but rebalances close-to-close, no next-open fill; result not comparable to oracle; 6 test files."),
"qstrader": ("PARK","INSTALL","N","N","MIT","Installed/imported only; no commits since 2024-06; daily-bar oriented (DOCUMENTED_CLAIM)."),
"pysystemtrade": ("PARK","NO","N","N","GPL-3.0 (flag)","IB-centred futures system (README); 15 authors, active. Not executed."),
"qlib": ("PARK","NO","N","N","MIT","ML research platform; 27 commits/12 m; last release 2025-08. Not executed."),
"LEAN": ("PARK","NO","N","N","Apache-2.0","C#/.NET engine; healthy (441 commits, 35 authors) but a whole second runtime. Not executed."),
"vnpy": ("PARK","NO","N","N","MIT","5 authors, 4 test files; trading-platform oriented. Not executed."),
"cvxportfolio": ("ADAPT_CANDIDATE","EXEC","N","N","GPL-3.0 (flag)","PROVEN: simulator cost = exactly 10 bps of traded notional for a=0.001 (1000.0 of 1e6), and 4x size -> x4.000 (spread) / x8.000 (impact, exponent 1.5); deterministic. Bus factor 1: one author = 100 % of 375 commits/12 m. Last release 2025-07."),
"tcapy": ("REJECT","NO","Y","Y","Apache-2.0 (per LICENCE file)","README: needs Redis + Celery + Memcached + MongoDB/Arctic/KDB/InfluxDB + MySQL/Postgres; last commit 2022-05."),
"PyPortfolioOpt": ("ADOPT_REFERENCE","EXEC","N","N","MIT","PROVEN: long-only min-variance weights equal SLSQP oracle to 2.6e-9; deterministic; undeclared dep `packaging` (import failed in isolated venv)."),
"Riskfolio-Lib": ("ADOPT_REFERENCE","EXEC","N","N","BSD-3-Clause","PROVEN: weights match oracle to 5e-7; deterministic; heavy (85 dists, 963 MB); 4 authors, top 88 %."),
"skfolio": ("ADAPT_CANDIDATE","EXEC","N","N","BSD-3-Clause","PROVEN: weights match oracle to 3e-5 (looser solver tol); deterministic; strongest maintenance in class (52 releases/12 m, 25 authors, top 31 %). sklearn-style API needs adapter."),
"quantstats": ("PARK","EXEC","N","N","Apache-2.0","OBSERVED: Sharpe/max-DD identical to numpy (<=1e-15); report/plot oriented (349 MB env); one author 95 %."),
"empyrical-reloaded": ("ADOPT_REFERENCE","EXEC","N","N","Apache-2.0","PROVEN: Sharpe/max-DD equal numpy to 1e-15; undeclared dep `pytz` (isolated import failed); 0 commits/12 m (stable)."),
"pyfolio-reloaded": ("PARK","NO","N","N","Apache-2.0","Tear-sheet plotting; 0 commits/12 m. Not executed."),
"alphalens-reloaded": ("PARK","NO","N","N","Apache-2.0","Factor tear sheets; 0 commits/12 m. Not executed."),
"arch": ("PARK","NO","N","N","NCSA","Volatility models; healthy; outside the gaps tested. Not executed."),
"TA-Lib (python)": ("ADOPT_REFERENCE","EXEC","N","N","BSD-2-Clause","OBSERVED: wheel installs in 1 s, causal (prefix-consistency maxabs 0.0), RSI 20 k bars 0.17-0.19 ms; used as parity oracle for ta/pandas-ta (0.0 on RSI)."),
"pandas-ta": ("REJECT","EXEC","N","N","unknown (repo gone)","OBSERVED: GitHub repo twopirllc/pandas-ta not reachable (git asks credentials); only pre-release 0.4.71b0 on PyPI needing py>=3.12; when run without TA-Lib it matches TA-Lib means to 1e-16. Provenance risk."),
"ta": ("PARK","EXEC","N","N","MIT","OBSERVED: EMA identical to pandas ewm(adjust=False); RSI/ATR equal to talipp; last release 2023-11, 1 commit/12 m."),
"talipp": ("ADAPT_CANDIDATE","EXEC","N","N","MIT","PROVEN vs batch: RSI14 maxabs 2.8e-6, ATR14 0.0 vs `ta`; EMA seeds with SMA (2.4e-3 early, 7e-7 vs pandas ewm after 100 bars) — must be documented in any parity contract; 1 MB, pure python; last release 2025-09."),
"tsfresh": ("PARK","NO","N","N","MIT","Batch feature extraction; 6 commits/12 m. Not executed."),
"river": ("ADOPT_REFERENCE","EXEC","N","N","BSD-3-Clause","PROVEN: online mean/var equal numpy (mean 9e-21, var rel 8e-15), Rolling(Mean,100) 5.6e-19, EWMean 1e-19; P2 p99 rel err 9.8e-4; deterministic; 0.72 us/update; 299 commits/12 m."),
"tdigest": ("PARK","EXEC","N","N","MIT","OBSERVED: p99 on 50 k = 9.247e-4 vs exact 9.245e-4 but 1.29 s for 50 k updates (pure python); last release 2019, last commit 2022."),
"sketches-py (ddsketch)": ("ADOPT_REFERENCE","EXEC","N","N","Apache-2.0","PROVEN: relative error 0.99 % <= claimed 1 %; merge of two sketches gives same p99 error; 1 MB; last release 2024-04."),
"hdrhistogram (hdrh)": ("ADOPT_REFERENCE","EXEC","N","N","Apache-2.0","PROVEN: p99 rel err 5.6e-6 with 3 significant digits; 5 MB; 6 commits/12 m."),
"exchange_calendars": ("ADOPT_REFERENCE","EXEC","N","N","Apache-2.0","PROVEN vs known dates: 1758 NYSE sessions 2020-2026 identical to pandas_market_calendars; 14 early closes identical; 2025-01-09 (Carter day) and 2026-07-03 closed; DST closes 21:00Z (EST) / 20:00Z (EDT); 71 calendars; 0.18 s load; 14 authors."),
"pandas_market_calendars": ("PARK","EXEC","N","N","MIT","OBSERVED: identical NYSE results but it depends on exchange-calendars (requires exchange-calendars>=3.3): redundant layer; 211 calendar names."),
"python-holidays": ("PARK","INSTALL","N","N","MIT","Imported (version check) only; 83 authors, 690 commits/12 m. Not tested."),
"great_expectations": ("PARK","EXEC","N","N","Apache-2.0","OBSERVED: caught dup (8 rows), non-positive (3), null (3), high<low (5); ordering check returned no count; no native gap check; 267 MB / 35 dists; complexity not justified for 7 checks that plain pandas does in a few lines (plain_pandas_reference in dq_microtest.py)."),
"pandera": ("ADAPT_CANDIDATE","EXEC","N","N","MIT","OBSERVED: lazy validation returned a failure-case table (105 rows) covering uniqueness, positivity, nullability, monotonicity, cross-column OHLC; 11 MB; 56 authors; gap detection needs a custom check."),
"soda-core": ("REJECT","NO","N","N","Elastic License 2.0 (not OSI)","LICENSE file at HEAD is ELv2; PyPI license field says Proprietary."),
"pointblank (python)": ("PARK","EXEC","N","N","MIT","OBSERVED: 3 steps reported 2/1/1 failures on a 10-row polars frame; young port (0.27.0), 92 % one author."),
"whylogs": ("REJECT","NO","N","N","Apache-2.0","0 commits in 12 m, last commit 2025-01-10, last release 2024-12."),
"frictionless-py": ("PARK","EXEC","N","N","MIT","OBSERVED: duplicate-row (4) and deviated-value (5) found on CSV; safe-path rule requires relative paths; resource-oriented, not time-series aware."),
"pydantic": ("PARK","NO","N","N","MIT","Row-level model validation; not executed as a DQ component."),
"TimescaleDB": ("ADAPT_CANDIDATE","EXEC","N","N","Apache-2.0 core + Timescale License features (flag)","OBSERVED on PG16 (2.30.2): hypertable bars byte-equal to native partitioning; 1-min OHLC query 5.6 ms vs 10.1/10.2 ms plain/native; compression 397.7->29.4 MB (13.5x) and continuous aggregate ran with `timescaledb.license=timescale`. Needs shared_preload_libraries + restart + 3rd-party apt repo (in-PG, no second service)."),
"pg_partman": ("ADOPT_REFERENCE","EXEC","N","N","PostgreSQL License","OBSERVED: create_parent(p_premake=4) created 10 child tables; packaged in Ubuntu noble; 20 commits/12 m. Native declarative partitioning did the same query with no extension."),
"QuestDB": ("PARK","NO","Y","Y","Apache-2.0","Separate server + datastore (violates one-authoritative-store doctrine); release download blocked (403) so not executed."),
"ClickHouse": ("PARK","EXEC","Y","Y","Apache-2.0","OBSERVED clickhouse-local 26.10: ASOF JOIN semantics correct (inclusive/strict) but needs >=1 equality key and an unmatched row returns 0, not NULL (join_use_nulls off) — silent missing-evidence-as-zero hazard; 866 MB binary. Git stats not collected (clone too large)."),
"DuckDB": ("ADOPT_REFERENCE","EXEC","N","N","MIT","PROVEN: ASOF join (inclusive and strict) equals pandas.merge_asof and polars.join_asof on 50 k x 200 k rows incl. exact-tie rows; 0 look-ahead violations; queries Parquet in place; read-only ATTACH of the live PG16 (3 M rows) worked. Compute-only use keeps it non-authoritative."),
"ArcticDB": ("PARK","EXEC","N","Y","Business Source License 1.1 (not OSI)","OBSERVED: as_of version and as_of timestamp reads return pre-restatement values (native PIT); but separate store (LMDB/S3) and BSL."),
"Apache Arrow (pyarrow)": ("ADOPT_REFERENCE","EXEC","N","N","Apache-2.0","OBSERVED: two Parquet writes of the same frame are byte-identical (sha256); 1.85 MB for 200 k quotes."),
"polars": ("ADOPT_REFERENCE","EXEC","N","N","MIT","PROVEN: join_asof equals pandas/duckdb on the tie-laden test; fastest of three (5 ms vs 21/61 ms)."),
"VictoriaMetrics": ("PARK","NO","Y","Y","Apache-2.0","Separate metrics server/datastore; not executed."),
"InfluxDB": ("PARK","NO","Y","Y","Apache-2.0 (LICENSE-APACHE seen)","Separate server/datastore; not executed."),
"tstables": ("REJECT","NO","N","Y","none found","Last commit 2015-10; no licence file."),
"sortedcontainers": ("PARK","INSTALL","N","N","Apache-2.0","Used transitively (nautilus, orderbook); no commits since 2024-03, last release 2021; not independently tested."),
}
