"""Candidate catalogue. (name, classes, github 'owner/repo', pypi name or None, primary language)
Classes: COLL collector, DL historical downloader, OB order-book, REPLAY replay engine, SIM event simulator,
TCM transaction-cost model, FEAT feature computation, ONLINE online statistics, PORT portfolio/risk,
BT backtest engine, CAL market calendar, DQ data-quality, TSS time-series storage."""
C = [
 ("ccxt","COLL,DL","ccxt/ccxt","ccxt","TypeScript/Python/PHP/C#/Go"),
 ("cryptofeed","COLL,OB","bmoscon/cryptofeed","cryptofeed","Python"),
 ("binance-public-data","DL","binance/binance-public-data",None,"Python/shell"),
 ("freqtrade","COLL,DL,BT","freqtrade/freqtrade","freqtrade","Python"),
 ("hummingbot","COLL,OB,SIM","hummingbot/hummingbot",None,"Python/Cython"),
 ("yfinance","DL","ranaroussi/yfinance","yfinance","Python"),
 ("openbb","DL,COLL","OpenBB-finance/OpenBB","openbb","Python"),
 ("databento-python","DL","databento/databento-python","databento","Python"),
 ("tardis-python","DL","tardis-dev/tardis-python","tardis-dev","Python"),
 ("pandas-datareader","DL","pydata/pandas-datareader","pandas-datareader","Python"),
 ("findatapy","DL,COLL","cuemacro/findatapy","findatapy","Python"),
 ("hftbacktest","REPLAY,SIM,OB,TCM,BT","nkaz001/hftbacktest","hftbacktest","Rust/Python"),
 ("nautilus_trader","REPLAY,SIM,OB,BT,TCM,COLL","nautechsystems/nautilus_trader","nautilus_trader","Rust/Python/Cython"),
 ("abides-jpmc-public","SIM,OB","jpmorganchase/abides-jpmc-public",None,"Python"),
 ("abides-gym-markets","SIM,OB","abides-sim/abides",None,"Python"),
 ("orderbook (dyn4mik3)","OB","dyn4mik3/OrderBook","orderbook","Python"),
 ("vectorbt","BT","polakowo/vectorbt","vectorbt","Python/numba"),
 ("backtrader","BT","mementum/backtrader","backtrader","Python"),
 ("backtesting.py","BT","kernc/backtesting.py","backtesting","Python"),
 ("zipline-reloaded","BT,CAL","stefan-jansen/zipline-reloaded","zipline-reloaded","Python/Cython"),
 ("bt","BT,PORT","pmorissette/bt","bt","Python"),
 ("qstrader","BT","mhallsmoore/qstrader","qstrader","Python"),
 ("pysystemtrade","BT,PORT","robcarver17/pysystemtrade",None,"Python"),
 ("qlib","BT,FEAT,PORT","microsoft/qlib","pyqlib","Python/Cython"),
 ("LEAN","BT,REPLAY,DL","QuantConnect/Lean",None,"C#"),
 ("vnpy","BT,COLL","vnpy/vnpy","vnpy","Python"),
 ("cvxportfolio","TCM,PORT,BT","cvxgrp/cvxportfolio","cvxportfolio","Python"),
 ("tcapy","TCM","cuemacro/tcapy",None,"Python"),
 ("PyPortfolioOpt","PORT","robertmartin8/PyPortfolioOpt","pyportfolioopt","Python"),
 ("Riskfolio-Lib","PORT","dcajasn/Riskfolio-Lib","riskfolio-lib","Python"),
 ("skfolio","PORT","skfolio/skfolio","skfolio","Python"),
 ("quantstats","PORT","ranaroussi/quantstats","quantstats","Python"),
 ("empyrical-reloaded","PORT","stefan-jansen/empyrical-reloaded","empyrical-reloaded","Python"),
 ("pyfolio-reloaded","PORT","stefan-jansen/pyfolio-reloaded","pyfolio-reloaded","Python"),
 ("alphalens-reloaded","FEAT,PORT","stefan-jansen/alphalens-reloaded","alphalens-reloaded","Python"),
 ("arch","PORT,FEAT","bashtage/arch","arch","Python/Cython"),
 ("TA-Lib (python)","FEAT","TA-Lib/ta-lib-python","TA-Lib","C/Cython"),
 ("pandas-ta","FEAT","twopirllc/pandas-ta","pandas-ta","Python"),
 ("ta","FEAT","bukosabino/ta","ta","Python"),
 ("talipp","FEAT,ONLINE","nardew/talipp","talipp","Python"),
 ("tsfresh","FEAT","blue-yonder/tsfresh","tsfresh","Python"),
 ("river","ONLINE,FEAT","online-ml/river","river","Python/Rust"),
 ("tdigest","ONLINE","CamDavidsonPilon/tdigest","tdigest","Python"),
 ("sketches-py (ddsketch)","ONLINE","DataDog/sketches-py","ddsketch","Python"),
 ("hdrhistogram (hdrh)","ONLINE","HdrHistogram/HdrHistogram_py","hdrhistogram","Python"),
 ("exchange_calendars","CAL","gerrymanoim/exchange_calendars","exchange-calendars","Python"),
 ("pandas_market_calendars","CAL","rsheftel/pandas_market_calendars","pandas-market-calendars","Python"),
 ("python-holidays","CAL","vacanza/holidays","holidays","Python"),
 ("great_expectations","DQ","great-expectations/great_expectations","great-expectations","Python"),
 ("pandera","DQ","unionai-oss/pandera","pandera","Python"),
 ("soda-core","DQ","sodadata/soda-core","soda-core","Python"),
 ("pointblank (python)","DQ","posit-dev/pointblank","pointblank","Python"),
 ("whylogs","DQ","whylabs/whylogs","whylogs","Python/Java"),
 ("frictionless-py","DQ","frictionlessdata/frictionless-py","frictionless","Python"),
 ("pydantic","DQ","pydantic/pydantic","pydantic","Python/Rust"),
 ("TimescaleDB","TSS","timescale/timescaledb",None,"C"),
 ("pg_partman","TSS","pgpartman/pg_partman",None,"SQL/PLpgSQL"),
 ("QuestDB","TSS","questdb/questdb",None,"Java/Rust"),
 ("ClickHouse","TSS","ClickHouse/ClickHouse",None,"C++"),
 ("DuckDB","TSS,FEAT","duckdb/duckdb","duckdb","C++"),
 ("ArcticDB","TSS","man-group/ArcticDB","arcticdb","C++/Python"),
 ("Apache Arrow (pyarrow)","TSS","apache/arrow","pyarrow","C++/Python"),
 ("polars","TSS,FEAT","pola-rs/polars","polars","Rust/Python"),
 ("sortedcontainers","OB,ONLINE","grantjenks/python-sortedcontainers","sortedcontainers","Python"),
 ("VictoriaMetrics","TSS","VictoriaMetrics/VictoriaMetrics",None,"Go"),
 ("InfluxDB","TSS","influxdata/influxdb",None,"Rust"),
 ("tstables","TSS","afiedler/tstables",None,"Python"),
]
