"""Doctrine outcomes (claude.md): ADOPT / ADAPT / PARK / REJECT, per source. No integration claim; 'ADAPT' = worth forward PIT capture / further external study."""
ADJ = {
 "bc_charts": ("PARK", "Free and convenient but aggregates are re-served without vintages; no incremental evidence (14 blockchain.info series tested, none significant). Prefer deriving own aggregates from blocks (blockstream) if on-chain is pursued."),
 "mempool_space": ("ADAPT", "Only source of LIVE mempool/fee-market state (no history exists) => forward capture with own receipt timestamps is the only way to ever test mempool signals; mining aggregates null in tests."),
 "blockstream": ("ADAPT", "PIT-native ledger data; own aggregation removes the vintage problem of chart APIs. Value unproven (chart-derived proxies null)."),
 "blockchair": ("PARK", "Snapshot-only on free tier; nothing beyond blockstream/mempool.space."),
 "defillama_stable": ("ADAPT", "Stablecoin supply change is only partly independent of price (R2adj 0.28); its raw next-day-return signal (DeltaR2 +0.39 %, BH q 0.97) is not significant; needs forward vintage capture because history is recomputed."),
 "gdelt_doc": ("PARK", "server limit is 1 request per 5 s (429 on 2 of 3 probes spaced 2.5 s; the third returned 200); DOC API is rolling ~3 months so cannot support a 3-year test. Bulk GKG/Events (DATEADDED) is the PIT-friendly route: not executed."),
 "rss_crypto": ("PARK", "No history; usable only via forward capture with receipt stamps; value untested."),
 "rss_fed": ("PARK", "Event calendar/PIT value plausible for event studies; not tested here."),
 "hn_algolia": ("ADAPT", "Free, PIT-native item timestamps, independent of price (R2adj 0.08); tested null. Use item-level created_at rather than nbHits. Cheap forward test candidate."),
 "stocktwits": ("PARK", "Recent window only; redistribution forbidden (DOCUMENTED_CLAIM)."),
 "reddit_json": ("REJECT", "Blocked from egress (403) and restrictive terms (DOCUMENTED_CLAIM)."),
 "bluesky": ("PARK", "Reachable via public AppView but 1/3 probe failed with 401/None; social coverage of finance small and client-declared createdAt."),
 "gtrends": ("REJECT", "No official API; every query re-sampled; scraping prohibited (DOCUMENTED_CLAIM); no PIT possible."),
 "wikipedia_pv": ("PARK", "Attention proxy is largely a price reaction (Bitcoin views R2adj 0.34, Cryptocurrency 0.20); null incremental. Keep only as a control."),
 "fear_greed": ("REJECT", "Composite includes volatility/momentum/volume (documented) and is 49 % explained by the price-side matrix: PRICE_DERIVATIVE_ONLY."),
 "polymarket": ("ADAPT", "PIT-native trade/price time, fully independent by construction; contracts are short-lived so no long history to test; needs forward capture on a fixed basket of macro/crypto markets."),
 "kalshi": ("ADAPT", "Same rationale as Polymarket; macro contracts (CPI/Fed) are the more relevant class; not tested."),
 "cftc_cot": ("ADAPT", "Weekly, real institutional positioning independent of price at daily lens (R2adj 0.14-0.24), documented release rule; null in test (lev net BTC ret DeltaR2 -0.74 %). Naive Tuesday-dating would leak 3-4 days (see 06). Needs vintage capture."),
 "etf_farside": ("PARK", "Most direct ETF flow series but Cloudflare-blocked; only issuer-page capture possible."),
 "etf_ssga_gld": ("PARK", "Snapshot only; history by own capture; not tested."),
 "sec_edgar": ("PARK", "PIT-native acceptanceDateTime (13F/Form 4/8-K) - strongest PIT source found but low frequency; not tested."),
 "fiscal_dts": ("ADAPT", "TGA liquidity series independent of price (R2adj 0.05); null for BTC/gold in this test; PIT via T+1 rule; low cost to keep capturing."),
 "nyfed": ("PARK", "Covered in report 005; not re-tested here."),
 "gh_playground": ("REJECT", "Table content changed between two identical queries 14 min apart and has holes (2024-06..2025-08) and no rows after 2026-07-02: no stability contract. Use GH Archive files instead."),
 "gharchive": ("ADAPT", "Immutable PIT-native hourly files (Last-Modified = publication). Heavy (~100 MB/hour) - process forward incrementally. Developer-activity tests (via playground copy) null; independent of price."),
 "github_rest": ("PARK", "Blocked by this session's scope policy, not a provider verdict; commit dates client-set."),
 "npm_pypi": ("PARK", "npm long history is free; pypistats 180 d; mirror/bot restatement; not tested."),
 "portwatch": ("PARK", "Genuinely new real-economy data (independent of price, R2adj <0.08) but nowcast is revised and null for crude in this test; keep for vintage-captured study."),
 "eia_files": ("ADAPT", "Scheduled, official, independent of price (R2adj ~0); null for WTI here (single 3-year sample, 173 weeks). Weekly frequency limits power."),
 "eia_api": ("PARK", "Same data as files; key required, not executed."),
 "gie_agsi": ("PARK", "Requires key; not executed; EU gas storage relevant to gas only."),
 "openmeteo": ("PARK", "Archive is ERA5 reanalysis (NOT PIT); PIT-like historical-forecast API rate-limited (429) from this egress. HDD/CDD null for natgas here."),
 "nws": ("PARK", "Forecast text replaced; needs forward capture; not tested."),
 "noaa_ndbc": ("PARK", "Rolling 45 d; niche."),
 "deribit_dvol": ("PARK", "See report 005; implied vol is price-derived by construction for information purposes; (one probe hit gateway 502 CONNECT rejection)."),
 "binance_vision": ("ADAPT", "Immutable files, checksummed, PIT-native; OI/positioning already in the baseline; long/short account ratio is price-derived (R2adj 0.46) and taker ratio a volume derivative."),
 "exchange_reserves": ("PARK", "Not free at useful resolution; not executed."),
 "baltic_shipping": ("PARK", "Paid; not executed."),
 "ais_open": ("PARK", "Needs account/receiver sharing; not executed."),
}
