"""Source catalogue for alternative_data_v1. Fields marked DOC come from provider documentation as remembered/known and were NOT re-verified in this run
(label DOCUMENTED_CLAIM); fields marked OBS come from executed probes (results/probe_results.json). Nothing here reads private AurumShift code."""
# cat: category ; probe: list of (label,url,params,headers) ; kind: expected content
S = []
def add(id, cat, name, probes, access, cost, history, latency, ts_sem, rev_sem, licence, coverage, rate, doc_note=""):
    S.append(dict(id=id, cat=cat, name=name, probes=probes, access=access, cost=cost, history=history, latency=latency, ts_sem=ts_sem,
                  rev_sem=rev_sem, licence=licence, coverage=coverage, rate=rate, doc_note=doc_note))
BC = "https://api.blockchain.info/charts/"
add("bc_charts", "on-chain", "Blockchain.com Charts API", [("n-transactions", BC + "n-transactions", {"timespan": "30days", "format": "json"}, None), ("mempool-size", BC + "mempool-size", {"timespan": "7days", "format": "json"}, None)],
    "keyless REST", "free", "2009-> (daily, OBS: 1300d pulled)", "aggregates lag; cache-control max-age 4h (OBS)", "x = period start (unix s); no publication time per row", "values regenerated server-side; no vintage/rev flag (Last-Modified = fetch time, OBS)", "ToS not verified (UNKNOWN); attribution asked (DOC)", "BTC only", "undocumented; 429 not seen at 18 calls/13 s (OBS)")
add("mempool_space", "mempool", "mempool.space REST (blocks/fees/mining)", [("fees_recommended", "https://mempool.space/api/v1/fees/recommended", None, None), ("blocks_fees_3y", "https://mempool.space/api/v1/mining/blocks/fees/3y", None, None), ("mempool_live", "https://mempool.space/api/mempool", None, None)],
    "keyless REST/WS", "free", "mining stats to 3y+ (OBS); mempool/fee-histogram LIVE ONLY (no history endpoint)", "sub-second live (DOC); block-level stats after block", "block timestamp (miner-set, +-2h tolerance, DOC BIP113) for mining series; live endpoints no history", "reorgs can rewrite recent blocks; aggregate series not versioned", "AGPL software; public API fair-use (DOC)", "BTC only", "rate limited per IP, unpublished thresholds (DOC)")
add("blockstream", "on-chain", "Blockstream Esplora", [("tip", "https://blockstream.info/api/blocks/tip/height", None, None), ("fee_est", "https://blockstream.info/api/fee-estimates", None, None)],
    "keyless REST", "free", "full chain via block/tx paging (no aggregates)", "live", "block/tx times native (blocktime)", "immutable after ~6 confs (reorg risk before)", "Blockstream public API terms (UNKNOWN exact)", "BTC/Liquid", "unpublished")
add("blockchair", "on-chain", "Blockchair stats", [("stats", "https://api.blockchair.com/bitcoin/stats", None, None)], "keyless (1440 req/day free DOC); key for more", "free tier", "current stats; history via paid dumps (DOC)", "live", "snapshot time in `context`", "n/a", "ToS restricts commercial (DOC)", "many chains", "1440/day free (DOC)")
add("defillama_stable", "on-chain", "DefiLlama stablecoins & TVL", [("stable_all", "https://stablecoins.llama.fi/stablecoincharts/all", None, None), ("tvl_hist", "https://api.llama.fi/v2/historicalChainTvl", None, None)],
    "keyless REST", "free", "2017-> daily (OBS)", "~hourly refresh (Last-Modified OBS)", "date = day (unix); no publication time", "history re-computed when adapters change (DOC/inference); no vintages", "CC-BY-like/attribution (DOC, not verified)", "multi-chain", "generous; undisclosed")
add("gdelt_doc", "news", "GDELT DOC 2.0 API", [("timelinevol", "https://api.gdeltproject.org/api/v2/doc/doc", {"query": "bitcoin", "mode": "timelinevol", "format": "json", "timespan": "1week"}, None)],
    "keyless REST", "free", "rolling ~3 months (DOC); bulk GKG/Events since 2013/2015", "15 min (DOC)", "DATEADDED in bulk files = ingest time (PIT-friendly, DOC)", "DOC API is recomputed on query; bulk files immutable", "open, attribution (DOC)", "global news", "1 request per 5 s (OBS: server message); 429 when violated")
add("rss_crypto", "RSS", "Crypto-news RSS (Cointelegraph)", [("rss", "https://cointelegraph.com/rss", None, None)], "keyless RSS", "free", "recent items only (~30)", "minutes", "pubDate per item (publisher-set)", "edits silently possible", "content copyright; headline use only (DOC)", "crypto", "n/a")
add("rss_fed", "RSS", "Federal Reserve press RSS", [("press_all", "https://www.federalreserve.gov/feeds/press_all.xml", None, None)], "keyless RSS", "free", "recent items", "minutes", "pubDate = release time", "documents rarely amended", "US gov public domain (DOC)", "US monetary policy", "n/a")
add("hn_algolia", "public social", "Hacker News (Algolia)", [("search_by_date", "https://hn.algolia.com/api/v1/search_by_date", {"query": "bitcoin", "tags": "story", "hitsPerPage": 5}, None)], "keyless REST", "free", "2006-> (OBS daily counts pulled)", "seconds", "created_at_i = post time (native)", "deletions/flagging change counts retroactively; nbHits inexact (OBS exhaustive=false)", "HN data terms UNKNOWN", "tech/crypto chatter", "10k/h per IP (DOC)")
add("stocktwits", "public social", "StockTwits symbol stream", [("btc_stream", "https://api.stocktwits.com/api/2/streams/symbol/BTC.X.json", None, None)], "keyless (limited)", "free", "last ~30 msgs, paginate back limited", "live", "created_at per message", "deletions", "ToS forbids redistribution (DOC)", "retail sentiment tags", "200/h unauth (DOC)")
add("reddit_json", "public social", "Reddit .json listing", [("r_bitcoin", "https://www.reddit.com/r/Bitcoin/new.json", {"limit": 5}, None)], "keyless but blocked to datacentre/proxy IPs", "free (commercial use needs licence, DOC)", "recent 1000 per listing", "live", "created_utc", "deletions", "restrictive (DOC)", "social", "strict")
add("bluesky", "public social", "Bluesky AppView", [("profile", "https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile", {"actor": "bsky.app"}, None)], "keyless public AppView", "free", "search recent; firehose live", "live", "createdAt (client-declared!) + indexedAt", "deletions", "open protocol", "social", "3000/5min (DOC)")
add("gtrends", "search/trend", "Google Trends (unofficial)", [("daily", "https://trends.google.com/trends/api/dailytrends", {"geo": "US"}, None)], "no official API; unofficial scrapers", "free", "2004->; re-normalised 0-100 per query window", "days", "window-relative index; values differ each query (sampling)", "re-sampled EVERY request (documented behaviour)", "ToS forbids scraping (DOC)", "search interest", "aggressive blocking")
add("wikipedia_pv", "search/trend", "Wikimedia pageviews REST", [("bitcoin_5d", "https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/user/Bitcoin/daily/20260901/20260905", None, None)], "keyless REST; UA required", "free", "2015-07->", "daily data ~ next day (DOC)", "day bucket (UTC)", "finalised daily; bot filtering agent=user classification retro-improved (DOC)", "CC0 data (DOC)", "all wiki articles", "200 req/s doc; shared-IP 429 seen (OBS)")
add("fear_greed", "search/trend", "alternative.me Fear & Greed", [("fng", "https://api.alternative.me/fng/", {"limit": 3}, None)], "keyless REST", "free", "2018-> daily (OBS)", "daily", "timestamp = day; no publication time", "unknown; composite of vol/momentum/volume/social/dominance", "attribution required (DOC)", "crypto", "60/min (DOC)")
add("polymarket", "prediction markets", "Polymarket Gamma+CLOB", [("gamma_markets", "https://gamma-api.polymarket.com/markets", {"limit": 5, "active": "true", "closed": "false"}, None), ("clob_time", "https://clob.polymarket.com/time", None, None)], "keyless read", "free", "per-market price history (clob prices-history, fidelity>=1min for active)", "seconds", "trade/price time native", "market resolution changes state; price history immutable-ish (DOC)", "ToS: read-only public data; geo restrictions on trading (DOC)", "event contracts, mostly politics/crypto price bands", "documented per-endpoint (DOC)")
add("kalshi", "prediction markets", "Kalshi public market data", [("markets", "https://api.elections.kalshi.com/trade-api/v2/markets", {"limit": 3}, None)], "keyless read for market data", "free", "candlesticks per market", "seconds", "created/updated time fields, trades timestamped", "settled markets fixed", "ToS (UNKNOWN exact)", "macro (CPI, Fed, gas) + others", "documented (DOC)")
add("cftc_cot", "CFTC positioning", "CFTC Public Reporting (Socrata) COT", [("tff_btc", "https://publicreporting.cftc.gov/resource/gpe5-46if.json", {"$limit": 1, "$where": "market_and_exchange_names like 'BITCOIN - CHICAGO MERCANTILE%'", "$order": "report_date_as_yyyy_mm_dd DESC"}, None)], "keyless Socrata (app token optional)", "free", "legacy 1986->, TFF 2006->, disaggregated 2006-> (DOC), BTC CME from 2017-12", "Tuesday data released Friday 15:30 ET (DOC); holiday shifts", "report_date = Tuesday as-of date; NO release timestamp per row (OBS)", "resubmissions/corrections possible; dataset overwritten in place, no vintages (Last-Modified per dataset OBS)", "US gov public domain (DOC)", "US futures", "Socrata throttling w/o token (DOC)")
add("etf_farside", "ETF/public flow", "Farside ETF flows", [("btc", "https://farside.co.uk/btc/", None, None)], "HTML behind Cloudflare challenge", "free (site)", "since Jan-2024 (DOC)", "daily evening", "date only", "restated by site (DOC)", "no explicit licence; scraping discouraged", "US spot BTC ETFs", "bot-blocked (OBS 403)")
add("etf_ssga_gld", "ETF/public flow", "SPDR GLD holdings (issuer)", [("gld_xlsx", "https://www.ssga.com/library-content/products/fund-data/etfs/us/holdings-daily-us-en-gld.xlsx", None, None)], "keyless file (current snapshot)", "free", "current file only; history by own capture (OBS: guessed file URL returned HTTP 404, so the file path is UNVERIFIED)", "daily", "as-of date inside file", "overwritten daily", "issuer terms (UNKNOWN)", "GLD gold tonnes", "n/a")
add("sec_edgar", "public government", "SEC EDGAR (13F, Form 4, 8-K)", [("submissions", "https://data.sec.gov/submissions/CIK0001838028.json", None, {"User-Agent": "aurumshift-external-research-lab research jf.guiffant@gmail.com"})], "keyless w/ declared UA", "free", "1994-> ; acceptedDateTime per filing (PIT-native!)", "seconds (public dissemination)", "acceptanceDateTime per filing (OBS: field present in submissions JSON, e.g. 2026-08-13T19:53:24Z for a VanEck Bitcoin ETF filing)", "amendments are new filings (10-K/A); originals kept", "US gov public domain", "US filers incl. ETF trusts", "10 req/s (DOC)")
add("fiscal_dts", "public government", "Treasury FiscalData DTS (TGA)", [("dts", "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/dts/operating_cash_balance", {"page[size]": 1, "sort": "-record_date"}, None)], "keyless REST", "free", "2005-> daily", "T+1 business day ~16:00 ET (DOC)", "record_date only; no publication stamp", "DTS values final; format changes 2022 (DOC)", "US gov public domain", "US Treasury cash", "generous (DOC)")
add("nyfed", "public government", "NY Fed markets (RRP/SOFR)", [("rrp", "https://markets.newyorkfed.org/api/rp/reverserepo/propositions/search.json", {"startDate": "2026-09-01", "endDate": "2026-09-10"}, None)], "keyless REST", "free", "2013-> ", "same day ~13:15 ET (DOC)", "operation date; revisionIndicator (see report 005)", "revisionIndicator present", "public domain-like", "US money markets", "n/a")
add("gh_playground", "GitHub ecosystem", "ClickHouse public playground github_events (GH Archive)", [("count", "https://play.clickhouse.com/", {"user": "play", "query": "SELECT count() FROM github_events WHERE repo_name='bitcoin/bitcoin' FORMAT TSV"}, None)], "keyless SQL over HTTP (read-only user `play`)", "free", "2011-> nominal; gaps OBS (see 02/06)", "~<1h behind (OBS max(created_at) vs now) but daily counts ended 2026-07-02 for tracked repos (OBS)", "created_at = GitHub event time (native)", "repo renames/deletions retroactive; no vintage", "GH Archive CC-BY-4.0-ish (DOC); playground is a demo, no SLA", "all public GitHub events", "shared demo cluster; quotas (DOC)")
add("gharchive", "developer activity", "GH Archive hourly dumps", [("hour_head", "https://data.gharchive.org/2026-09-01-0.json.gz", None, None)], "keyless file download", "free", "2011-> hourly files (~60-150 MB each)", "files ~1h after hour (DOC)", "created_at per event; file Last-Modified = publication (OBS header)", "immutable files", "CC-BY (DOC, unverified)", "all public GitHub events", "none documented")
add("github_rest", "GitHub ecosystem", "GitHub REST API", [("commit_activity", "https://api.github.com/repos/bitcoin/bitcoin/stats/commit_activity", None, None)], "token for useful limits", "free", "deep", "live", "commit author/committer dates (client-set!)", "history rewritable (force-push)", "ToS", "repos", "60/h unauth (DOC)", "blocked by THIS SESSION's repository-scope policy, not a provider verdict")
add("npm_pypi", "developer activity", "npm downloads / pypistats", [("npm", "https://api.npmjs.org/downloads/range/2026-09-01:2026-09-05/ethers", None, None), ("pypistats", "https://pypistats.org/api/packages/web3/overall", None, None)], "keyless REST", "free", "npm 2015->; pypistats 180 d only", "daily ~1 day", "day bucket", "bot/mirror traffic restated (DOC)", "public", "package ecosystems", "npm 429 at high rate (DOC)")
add("portwatch", "shipping", "IMF PortWatch (ArcGIS FeatureServer)", [("chokepoints", "https://services9.arcgis.com/weJ1QsnbMYJlCHdG/arcgis/rest/services/Daily_Chokepoints_Data/FeatureServer/0/query", {"where": "1=1", "outFields": "*", "resultRecordCount": 2, "f": "json"}, None)], "keyless ArcGIS query", "free", "2019-> daily", "published weekly, ~few days lag (DOC)", "date = transit day; no publication time", "nowcast model, historical values revised (DOC)", "CC-BY 4.0 (DOC)", "28 chokepoints, ~1400 ports", "ArcGIS maxRecordCount (2000 OBS pagination)")
add("eia_files", "energy inventories", "EIA weekly petroleum/gas files (xls)", [("crude_stocks", "https://www.eia.gov/dnav/pet/hist_xls/WCESTUS1w.xls", None, None)], "keyless xls; API v2 needs free key", "free", "1982-> weekly", "WPSR Wed 10:30 ET / WNGSR Thu 10:30 ET (DOC)", "week-ending date; no publication stamp", "final values only; revisions in monthly data (DOC)", "US gov public domain", "US inventories", "n/a")
add("eia_api", "energy inventories", "EIA API v2", [("root", "https://api.eia.gov/v2/", None, None)], "free API key (registration)", "free", "same", "same", "same", "same", "public domain", "US energy", "5k rows/req; key")
add("gie_agsi", "energy inventories", "GIE AGSI+ EU gas storage", [("api", "https://agsi.gie.eu/api", {"country": "eu", "from": "2026-09-20"}, None)], "free API key (x-key) required", "free", "2011->", "daily 18:00 CET, ~19:30 (DOC)", "gasDayStart + updatedAt (DOC fields)", "values are revised, `updatedAt` present (DOC)", "attribution (DOC)", "EU gas storage", "key")
add("openmeteo", "weather", "Open-Meteo archive / historical-forecast", [("archive", "https://archive-api.open-meteo.com/v1/archive", {"latitude": 40.7, "longitude": -74, "start_date": "2024-01-01", "end_date": "2024-01-02", "daily": "temperature_2m_mean"}, None), ("hist_forecast", "https://historical-forecast-api.open-meteo.com/v1/forecast", {"latitude": 40.7, "longitude": -74, "start_date": "2024-01-01", "end_date": "2024-01-02", "hourly": "temperature_2m"}, None)], "keyless (non-commercial)", "free non-commercial; commercial paid", "archive 1940-> ERA5; historical-forecast 2022-> (stored model runs, PIT-ish, DOC)", "ERA5 lag ~5 d (DOC)", "valid time; archive is reanalysis (hindsight-assimilated) = NOT PIT", "ERA5T -> ERA5 revisions (DOC)", "CC-BY 4.0 for data; API non-commercial (DOC)", "global", "10k/day free (DOC); daily limit hit on hist-forecast (OBS)")
add("nws", "weather", "NWS api.weather.gov", [("root", "https://api.weather.gov/", None, None)], "keyless w/ UA", "free", "obs ~7 days; forecasts current only", "minutes", "issuance time", "forecast text replaced", "US gov public domain", "US", "undisclosed")
add("noaa_ndbc", "weather", "NOAA NDBC buoys realtime", [("41001", "https://www.ndbc.noaa.gov/data/realtime2/41001.txt", None, None)], "keyless", "free", "45 days rolling realtime", "hourly", "obs time", "QC revised in archive", "public domain", "ocean", "n/a")
add("deribit_dvol", "exchange flows where public", "Deribit public API (index/funding/OI)", [("index", "https://www.deribit.com/api/v2/public/get_index_price", {"index_name": "btc_usd"}, None), ("funding_hist", "https://www.deribit.com/api/v2/public/get_funding_rate_history", {"instrument_name": "BTC-PERPETUAL", "start_timestamp": 1735689600000, "end_timestamp": 1735862400000}, None)], "keyless REST/WS", "free", "funding history years (DOC); trades history deep", "ms", "usIn/usOut server stamps (see report 005)", "trades immutable", "ToS (UNKNOWN exact)", "BTC/ETH derivs", "20 req/s credit system (DOC)")
add("binance_vision", "exchange flows where public", "Binance Vision (data.binance.vision)", [("metrics", "https://data.binance.vision/data/futures/um/daily/metrics/BTCUSDT/BTCUSDT-metrics-2026-09-20.zip", None, None)], "keyless files", "free", "OI/long-short metrics since 2021-12 (OBS)", "next-day files (OBS Last-Modified)", "5-min bar times; file Last-Modified = publication", "files immutable (checksums)", "Binance Vision terms (DOC)", "Binance derivatives", "none documented")
add("exchange_reserves", "exchange flows where public", "Exchange wallet/reserve flows (Glassnode/CryptoQuant/Arkham)", [], "FREE TIER LIMITED / paid API", "paid for history+resolution (DOC)", "n/a", "n/a", "n/a", "n/a", "proprietary licence (DOC)", "labels proprietary", "n/a", "NOT EXECUTED: no keyless free source with history found; on-chain address-label clusters are vendor-derived")
add("baltic_shipping", "shipping", "Baltic Dry Index / freight indices", [], "paid (Baltic Exchange)", "paid (DOC)", "n/a", "n/a", "n/a", "n/a", "proprietary", "n/a", "n/a", "NOT EXECUTED: no free primary source found; Yahoo/Investing proxies are unofficial")
add("ais_open", "shipping", "AIS open feeds (AISHub, GFW)", [], "AISHub requires data-sharing; GFW token", "free w/ conditions", "n/a", "n/a", "n/a", "n/a", "conditional", "n/a", "n/a", "NOT EXECUTED: needs account/receiver sharing; PortWatch used as executed shipping proxy")
