"""PIT classification per source (hand-adjudicated from OBS probes + DOC). hist_class: PIT_NATIVE | LOOKAHEAD_RISK (historical rows). fwd: forward-capture readiness.
Rule (mission section 4): historical rows without historical publication timestamps => LOOKAHEAD_RISK. A source is PIT_NATIVE only if each row carries an event/publication time
that cannot be revised after the fact (ledger/trade/filing/file time). PIT_ADAPTABLE = LOOKAHEAD_RISK for history but usable point-in-time if the consumer captures vintages forward (or a documented release rule gives a conservative lag)."""
PIT = {
 "bc_charts": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "aggregates re-served with Last-Modified=fetch time; capture forward daily + keep vintages"),
 "mempool_space": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "live mempool has no history: forward capture is the ONLY way; mining series aggregated ex-post"),
 "blockstream": ("PIT_NATIVE", "PIT_NATIVE", "block/tx timestamps on-ledger; derive own aggregates; reorg buffer of ~6 blocks"),
 "blockchair": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "snapshot only; history paid"),
 "defillama_stable": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "history recomputed when adapters change (DOC/INFERENCE); forward snapshots needed"),
 "gdelt_doc": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "DOC API recomputes; bulk GKG/Events files carry DATEADDED (ingest) => bulk files PIT_NATIVE (DOCUMENTED_CLAIM, not executed)"),
 "rss_crypto": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "no history at all; pubDate publisher-set; forward capture with own receipt stamp"),
 "rss_fed": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "no deep history in feed; forward capture"),
 "hn_algolia": ("PIT_NATIVE", "PIT_NATIVE", "created_at_i is post time; counts retro-change via deletions/flags => use item timestamps not nbHits (nbHits inexact OBS)"),
 "stocktwits": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "recent window only"),
 "reddit_json": ("LOOKAHEAD_RISK", "NOT_READY", "blocked from test egress; recent 1000 only"),
 "bluesky": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "createdAt client-declared; use indexedAt from own firehose capture"),
 "gtrends": ("LOOKAHEAD_RISK", "NOT_READY", "re-sampled every request; no official API"),
 "wikipedia_pv": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "day-bucket, finalised next day, classification refinements retro; no per-row publication time"),
 "fear_greed": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "no publication time, methodology undisclosed; price-derived anyway"),
 "polymarket": ("PIT_NATIVE", "PIT_NATIVE", "trades/price points carry event time; resolution state is mutable"),
 "kalshi": ("PIT_NATIVE", "PIT_NATIVE", "trades timestamped; settlement final"),
 "cftc_cot": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "as-of Tuesday, release rule Fri 15:30 ET documented; dataset overwritten in place, no vintages; holiday delays"),
 "etf_farside": ("LOOKAHEAD_RISK", "NOT_READY", "blocked by Cloudflare challenge; site restates"),
 "etf_ssga_gld": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "current snapshot overwritten daily; capture forward"),
 "sec_edgar": ("PIT_NATIVE", "PIT_NATIVE", "acceptanceDateTime per filing; amendments are new filings (OBS: acceptanceDateTime present in submissions JSON; amendments-as-new-filings is DOCUMENTED_CLAIM)"),
 "fiscal_dts": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "record_date only; release rule T+1 documented"),
 "nyfed": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "revisionIndicator present but no vintage store (see report 005)"),
 "gh_playground": ("PIT_NATIVE", "PIT_NATIVE", "created_at = event time; BUT coverage holes (2024-06-06..2025-09) => completeness not guaranteed (OBS)"),
 "gharchive": ("PIT_NATIVE", "PIT_NATIVE", "immutable hourly files, Last-Modified = publication time (OBS header)"),
 "github_rest": ("LOOKAHEAD_RISK", "NOT_READY", "not executed (session policy); author dates client-set, history rewritable"),
 "npm_pypi": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "restated for bots/mirrors; pypistats 180 d only"),
 "portwatch": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "AIS nowcast revised (DOC); publish weekly; vintage capture needed"),
 "eia_files": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "release calendar documented; final values only"),
 "eia_api": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "same as files; key needed (not executed)"),
 "gie_agsi": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "updatedAt field documented (DOC) but key needed (not executed)"),
 "openmeteo": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "archive=ERA5 reanalysis NOT PIT; historical-forecast API (stored runs) is PIT-like (DOC) but was rate-limited (OBS 429)"),
 "nws": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "forecast text replaced; forward capture"),
 "noaa_ndbc": ("LOOKAHEAD_RISK", "PIT_ADAPTABLE", "rolling 45 d"),
 "deribit_dvol": ("PIT_NATIVE", "PIT_NATIVE", "trades/funding prints carry exchange time; server stamps (report 005)"),
 "binance_vision": ("PIT_NATIVE", "PIT_NATIVE", "immutable daily files with checksums; file Last-Modified = publication (OBS)"),
 "exchange_reserves": ("LOOKAHEAD_RISK", "NOT_READY", "not executed"),
 "baltic_shipping": ("LOOKAHEAD_RISK", "NOT_READY", "not executed"),
 "ais_open": ("LOOKAHEAD_RISK", "NOT_READY", "not executed"),
}
